version: "3.8"
services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=aliasaddik
        - MONGO_INITDB_ROOT_PASSWORD=12345
    restart: unless-stopped
    ports:
      - "27017:27017"
     
  # mongo-express:
  #   image: mongo-express
  #   container_name: mexpress
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=aliasaddik
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
  #     - ME_CONFIG_MONGODB_URL=mongodb://aliasaddik:12345@mongo:27017/?authSource=admin
      
  #   links:
  #     - mongo
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"
  
  web:
    build: ..
    image: web:1.0.0
    container_name: 'web'
    ports:
           - "9090:9090"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=aliasaddik
        - MONGO_INITDB_ROOT_PASSWORD=12345
    restart: on-failure
    depends_on:
      - mongo



  frontend: 
    build: ../github-users-app  
      
    image: frontend:1.0.0  
    container_name: 'frontend'  
    ports:  
      - "8080:8080"
  
    stdin_open: true 
    tty: true  
    depends_on:  
      - web
  test:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:10.2.0"
    stdin_open: true 
    tty: true  
 
    depends_on: [frontend]
   
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://frontend:8080
    working_dir: /e2e
    volumes:
        - ./:/e2e
  
    


  
  