name: ci
# run all tests on the main branch
on:
  push:
    branches:
      - main
jobs:
  test-http:
    runs-on: ubuntu-20.04
    steps:
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
      
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
        
     - name: Check out code 🛎
       uses: actions/checkout@v2

      # run utility services in the background
      # using docker-compose (see docker-compose.yml file)
     - name: Run docker-compose
       run: docker-compose  -f mongo-docker-compose.yaml up -d
     -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
     - name: docker push
   
       run: |
         docker tag todo-project_web:latest aliasaddik/aliasaddik-todo:latest
         docker push aliasaddik/aliasaddik-todo:latest


     
